/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.poly.vn.lab6;

/**
 *
 * @author QUANGVU
 */
public class LAB_4 extends javax.swing.JPanel {

    /**
     * Creates new form LAB_4
     */
    public LAB_4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        TXTUNIT = new java.awt.Button();
        TXTDOZEN = new java.awt.Button();
        TXTHUNDRED = new java.awt.Button();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TXTUNIT.setLabel("button1");
        TXTUNIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTUNITActionPerformed(evt);
            }
        });
        add(TXTUNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        TXTDOZEN.setLabel("button1");
        TXTDOZEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTDOZENActionPerformed(evt);
            }
        });
        add(TXTDOZEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        TXTHUNDRED.setLabel("button1");
        TXTHUNDRED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTHUNDREDActionPerformed(evt);
            }
        });
        add(TXTHUNDRED, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jTextField1.setText("0");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 60, -1));

        jTextField2.setText("0");
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 60, -1));

        jTextField3.setText("0");
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, -1));

        jLabel1.setText("Trăm");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, -1));

        jLabel2.setText("Đơn vị");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel3.setText("Chục");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void TXTUNITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTUNITActionPerformed
        // TODO add your handling code here:
        LOTTETHERD_B4 th = new LOTTETHERD_B4(TXTUNIT);
        th.start();
        TXTUNIT.setEnabled(false);
    }//GEN-LAST:event_TXTUNITActionPerformed

    private void TXTHUNDREDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTHUNDREDActionPerformed
        // TODO add your handling code here:
        LOTTETHERD_B4 th = new LOTTETHERD_B4(TXTHUNDRED);
        th.start();
        TXTHUNDRED.setEnabled(false);
    }//GEN-LAST:event_TXTHUNDREDActionPerformed

    private void TXTDOZENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTDOZENActionPerformed
        // TODO add your handling code here:
        LOTTETHERD_B4 th = new LOTTETHERD_B4(TXTDOZEN);
        th.start();
        TXTDOZEN.setEnabled(false);

    }//GEN-LAST:event_TXTDOZENActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button TXTDOZEN;
    private java.awt.Button TXTHUNDRED;
    private java.awt.Button TXTUNIT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
