/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FROM;

import java.awt.Color;
import java.sql.Time;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Empoly.Empoly;
import Empoly.NhanVienTim;
import com.sun.source.tree.BreakTree;

/**
 *
 * @author QUANGVU
 */
public class FROMNV extends javax.swing.JFrame {

    int index = 0;

    public FROMNV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TXTB1 = new javax.swing.JTable();
        txtMNV = new javax.swing.JTextField();
        txtPrev = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        txtHVT = new javax.swing.JTextField();
        btnTime = new javax.swing.JButton();
        txtmnvv = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        txtDelete1 = new javax.swing.JButton();
        txtFix = new javax.swing.JButton();
        txtOut = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        txtOpen = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNext = new javax.swing.JButton();
        btnPrist = new javax.swing.JButton();
        CurenIndex = new javax.swing.JLabel();
        txtTim = new javax.swing.JButton();
        j = new javax.swing.JTextField();
        txtLuong = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TXTB2 = new javax.swing.JTable();

        jLabel13.setText("Mã Nhân Viên ");

        TXTB1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Họ Và Tên", "Tuổi", "Email", "Lương"
            }
        ));
        TXTB1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TXTB1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        TXTB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXTB1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TXTB1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPrev.setText("<<");
        txtPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrevActionPerformed(evt);
            }
        });

        btnAbout.setText(">|");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        btnTime.setText("Xem Giờ");
        btnTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimeActionPerformed(evt);
            }
        });

        txtmnvv.setText("Mã Nhân Viên ");

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        jLabel10.setText("Họ Và Tên");

        jLabel7.setText("Lương");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        txtDelete1.setText("Delete");
        txtDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDelete1ActionPerformed(evt);
            }
        });

        txtFix.setText("Sửa ");
        txtFix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFixMouseClicked(evt);
            }
        });
        txtFix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFixActionPerformed(evt);
            }
        });

        txtOut.setText("Exit");
        txtOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutActionPerformed(evt);
            }
        });

        jButton18.setText("New");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        txtOpen.setText("Open");
        txtOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOpenMouseClicked(evt);
            }
        });
        txtOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDelete1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(txtOpen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtOpen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtOut)
                .addGap(25, 25, 25))
        );

        jLabel11.setText("Tuổi");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Quản Lý Nhân Viên");

        jLabel12.setText("Email");

        txtNext.setText(">>");
        txtNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNextActionPerformed(evt);
            }
        });

        btnPrist.setText("|<");
        btnPrist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPristActionPerformed(evt);
            }
        });

        CurenIndex.setText("Record : ....");

        txtTim.setText("Tim nhân viên");
        txtTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimActionPerformed(evt);
            }
        });

        j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActionPerformed(evt);
            }
        });
        j.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jKeyReleased(evt);
            }
        });

        TXTB2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Họ Và Tên", "Tuổi", "Email", "Lương"
            }
        ));
        TXTB2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TXTB2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        TXTB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXTB2MouseClicked(evt);
            }
        });
        TXTB2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTB2KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(TXTB2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrist, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNext, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CurenIndex))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTim)
                                .addGap(18, 18, 18)
                                .addComponent(j, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmnvv)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(82, 82, 82)
                                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(50, 50, 50)
                                            .addComponent(txtHVT, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel12))
                                            .addGap(71, 71, 71)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(txtMNV, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(128, 128, 128)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(55, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmnvv))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTim)
                            .addComponent(j, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTime, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbout)
                    .addComponent(txtNext)
                    .addComponent(txtPrev)
                    .addComponent(btnPrist)
                    .addComponent(CurenIndex))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// ĐỎ DỬ LIỆU VÀO MẢNG
    private ArrayList<Empoly> arrnhanvien = new ArrayList<>();

    public void LoadDataToArrayList(int vitri) {
        Empoly nv = new Empoly();
        nv.setId(txtMNV.getText());
        nv.setName(txtHVT.getText());
        nv.setAge(Integer.parseInt(txtAge.getText()));
        nv.setEmail(txtEmail.getText());
        nv.setLuong(Double.parseDouble(txtLuong.getText()));
        nv.setD arrnhanvien
        .add(nv);
    }
    // ĐỎ DỬ LIÊU XUỐNG JTABLE

    public void LoadDataArrayListToTable(int vitri) {
        DefaultTableModel model = (DefaultTableModel) TXTB2.getModel(); // DefaultTableModel lưu trữ dữ liệu cho JTable 
        model.setRowCount(0);
        for (Empoly nv : arrnhanvien) {
            model.addRow(new Object[]{nv.getId(), nv.getName(), nv.getAge(),
                nv.getEmail(), String.format("%.2f", nv.getLuong())});
        }
    }

    private void txtPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrevActionPerformed

        vitri = vitri - 1;
        LoadDataControl(vitri);
        TXTB2.setRowSelectionInterval(vitri, vitri);
        CurenIndex.setText(Record());

    }//GEN-LAST:event_txtPrevActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        vitri = arrnhanvien.size() - 1;
        LoadDataControl(vitri);
        TXTB2.setRowSelectionInterval(vitri, vitri);
        CurenIndex.setText(Record());

    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimeActionPerformed
        // TODO add your handling code here:
        TIMEE time = new TIMEE(btnTime);
        time.start();
        btnTime.setEnabled(true);
    }//GEN-LAST:event_btnTimeActionPerformed

    private void TXTB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTB1MouseClicked

    }//GEN-LAST:event_TXTB1MouseClicked


    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        if (txtMNV.getText().equals("")) {
            JOptionPane.showConfirmDialog(this, "Xin Mời Nhập Mã Nhân Viên");
            txtMNV.setBackground(Color.red);
            return;
        } else {
            txtMNV.setBackground(Color.white);
        }
        if (txtHVT.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập tên");
            txtHVT.setBackground(Color.red);
            return;
        } else {
            txtHVT.setBackground(Color.white);
        }
        if (txtAge.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập tuổi");
            txtAge.setBackground(Color.red);
            return;
        } else {
            txtAge.setBackground(Color.white);
        }
        // tuổi phải lớn hơn 15 và nhỏ hơn 55
        if (Integer.parseInt(txtAge.getText()) < 15) {
            JOptionPane.showMessageDialog(this, "Tuổi phải lớn hơn 15 và nhỏ hơn 65");
            return;
        }
        if (Integer.parseInt(txtAge.getText()) > 65) {
            JOptionPane.showMessageDialog(this, "Tuổi phải nhỏ hơn 65 và nhỏ hơn 15");
            return;
        }
        if (txtEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập Email");
            txtEmail.setBackground(Color.red);
            return;
        } else {
            txtEmail.setBackground(Color.white);
        }
        // Kiểm tra định dạng email
        Pattern p = Pattern.compile("^[A-Za-z0-9]+\\@[A-Za-z0-9]+\\.[A-Za-z0-9]+$");
        if (p.matcher(txtEmail.getText()).find()) {

        } else {
            JOptionPane.showConfirmDialog(null, "email không đúng định dạng");
            return;
        }
        if (txtLuong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập lương");
            txtLuong.setBackground(Color.red);
            return;
        } else {
            txtLuong.setBackground(Color.white);
        }
        // Lương phải lớn hơn 5 triêu 
        if (Double.parseDouble(txtLuong.getText()) < 5000000) {
            JOptionPane.showMessageDialog(this, "Lương phải lớn hơn 5 triệu");
            return;
        }

        LoadDataToArrayList(vitri);
        LoadDataArrayListToTable(vitri);

        // JOptionPane.showMessageDialog(null, "Thêm Thành Côngg");

    }//GEN-LAST:event_btnThemActionPerformed

    // lấy vị trí dòng
    int vitri = -1;

    public void LoadDataControl(int vitri) {
        vitri = TXTB2.getSelectedRow();//getSelectedRow lấy vị trí dòng sau đó đổ lên ô nhập
        txtMNV.setText(arrnhanvien.get(vitri).getId());
        txtHVT.setText(arrnhanvien.get(vitri).getName());
        txtAge.setText(String.valueOf(arrnhanvien.get(vitri).getAge()));
        txtEmail.setText(arrnhanvien.get(vitri).getEmail());
        txtLuong.setText(String.valueOf(arrnhanvien.get(vitri).getLuong()));

    }
    private void txtDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDelete1ActionPerformed
        // TODO add your handling code here:
        if (vitri != -1) {
            arrnhanvien.remove(vitri);
            LoadDataArrayListToTable(vitri);
            JOptionPane.showMessageDialog(this, "Xóa thành công");

        } else {
            JOptionPane.showMessageDialog(this, "Chọn nhân viên để xóa");
            return;
        }
    }//GEN-LAST:event_txtDelete1ActionPerformed

    private void txtFixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFixActionPerformed
        Empoly nv = new Empoly();
        if (vitri != -1) {
            nv.setId(txtMNV.getText());
            nv.setName(txtHVT.getText());
            nv.setAge(Integer.parseInt(txtAge.getText()));
            nv.setEmail(txtEmail.getText());
            nv.setLuong(Double.parseDouble(txtLuong.getText()));
            arrnhanvien.set(vitri, nv);
            LoadDataArrayListToTable(vitri);
            JOptionPane.showMessageDialog(this, "Sửa thành công");
        } else {
            JOptionPane.showMessageDialog(this, " Chọn nhân viên để sửa ");
        }
    }//GEN-LAST:event_txtFixActionPerformed

    private void txtTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimActionPerformed

    }//GEN-LAST:event_txtTimActionPerformed

    private void txtOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutActionPerformed
        if (JOptionPane.showConfirmDialog(txtOut,
                "Are you sure you want to close this window?", "Close Window?",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_txtOutActionPerformed
    public void neww() {
        String a = "";
        txtMNV.setText(a);
        txtHVT.setText(a);
        txtHVT.setText(a);
        txtAge.setText(a);
        txtEmail.setText(a);
        txtLuong.setText(a);

    }
    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        this.neww();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void txtNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNextActionPerformed

        vitri = vitri + 1;
        LoadDataControl(vitri);
        TXTB2.setRowSelectionInterval(vitri, vitri);
        CurenIndex.setText(Record());

    }//GEN-LAST:event_txtNextActionPerformed


    private void btnPristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPristActionPerformed

        vitri = vitri = 0;
        LoadDataControl(vitri);
        TXTB2.setRowSelectionInterval(vitri, vitri);
        CurenIndex.setText(Record());
    }//GEN-LAST:event_btnPristActionPerformed

    private void TXTB1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TXTB1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTB1AncestorAdded

    private void txtFixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFixMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFixMouseClicked

    private void jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jActionPerformed

    private void txtOpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOpenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOpenMouseClicked

    private void txtOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOpenActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed
    public String Record() {
        return " Record :" + (vitri + 1) + " of " + arrnhanvien.size();
    }
    private void TXTB2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTB2MouseClicked
        vitri = TXTB2.getSelectedRow();
        CurenIndex.setText(Record());
        LoadDataControl(vitri);
    }//GEN-LAST:event_TXTB2MouseClicked

    ArrayList<NhanVienTim> l2 = new ArrayList<>();

    /*
    public void tim() {
        l2.clear();
        for (int i = 0; i < arrnhanvien.size(); i++) {
            if (arrnhanvien.get(i).getId().contains(txtTim.getText()) == true) {
                int vitri = i;
                String ma = arrnhanvien.get(i).getId();
                String hvt = arrnhanvien.get(i).getName();
                int tuoi = arrnhanvien.get(i).getAge();
                String email = arrnhanvien.get(i).getEmail();
                double luong = arrnhanvien.get(i).getLuong();
                NhanVienTim nvtim = new NhanVienTim(i, ma, hvt, tuoi, email, luong);

                l2.add(nvtim);
            }
        }
        ArrayListTimToTbale();
    }

    public void ArrayListTimToTbale() {
        DefaultTableModel model = (DefaultTableModel) TXTB2.getModel(); // DefaultTableModel lưu trữ dữ liệu cho JTable 
        model.setRowCount(0); // đi từ 0
        for (int i = 0; i < l2.size(); i++) {
            String ma = l2.get(i).getId();
            String hvt = l2.get(i).getName();
            int tuoi = l2.get(i).getAge();
            String email = l2.get(i).getEmail();
            double luong = l2.get(i).getLuong();

            Object[] row = new Object[]{ma, hvt, tuoi, email, luong};
            model.addRow(row);
        }
    }
    int co = 0;

    }
     */

    private void jKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jKeyReleased

    private void TXTB2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTB2KeyReleased

    }//GEN-LAST:event_TXTB2KeyReleased

    private void TXTB2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TXTB2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTB2AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FROMNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CurenIndex;
    private javax.swing.JTable TXTB1;
    private javax.swing.JTable TXTB2;
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnPrist;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTime;
    private javax.swing.JTextField j;
    private javax.swing.JButton jButton18;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtAge;
    private javax.swing.JButton txtDelete1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JButton txtFix;
    private javax.swing.JTextField txtHVT;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMNV;
    private javax.swing.JButton txtNext;
    private javax.swing.JButton txtOpen;
    private javax.swing.JButton txtOut;
    private javax.swing.JButton txtPrev;
    private javax.swing.JButton txtTim;
    private javax.swing.JLabel txtmnvv;
    // End of variables declaration//GEN-END:variables
}
