
import java.awt.Button;
import java.awt.Color;
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author QUANGVU
 */
public class B1 extends javax.swing.JFrame {

    /**
     * Creates new form B1
     */
    public B1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtJpanen = new javax.swing.JPanel();
        txtRed = new javax.swing.JButton();
        txtYellow = new javax.swing.JButton();
        txtGreen = new javax.swing.JButton();
        txtCenter = new javax.swing.JButton();
        txtNorth = new javax.swing.JButton();
        txtEast = new javax.swing.JButton();
        txtWest = new javax.swing.JButton();
        txtSouth = new javax.swing.JButton();
        txtFile = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtJpanen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtJpanen.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtJpanenAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txtRed.setText("Red");
        txtRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRedActionPerformed(evt);
            }
        });

        txtYellow.setText("Yellow");
        txtYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYellowActionPerformed(evt);
            }
        });

        txtGreen.setText("Green");
        txtGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGreenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txtJpanenLayout = new javax.swing.GroupLayout(txtJpanen);
        txtJpanen.setLayout(txtJpanenLayout);
        txtJpanenLayout.setHorizontalGroup(
            txtJpanenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtJpanenLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(txtRed, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(txtGreen)
                .addGap(18, 18, 18)
                .addComponent(txtYellow)
                .addContainerGap())
        );
        txtJpanenLayout.setVerticalGroup(
            txtJpanenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtJpanenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtJpanenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRed)
                    .addComponent(txtGreen)
                    .addComponent(txtYellow))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        txtCenter.setText("Center");
        txtCenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCenterActionPerformed(evt);
            }
        });

        txtNorth.setText("North");
        txtNorth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNorthActionPerformed(evt);
            }
        });

        txtEast.setText("East");
        txtEast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEastActionPerformed(evt);
            }
        });

        txtWest.setText("West");
        txtWest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWestActionPerformed(evt);
            }
        });

        txtSouth.setText("South");
        txtSouth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSouthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSouth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNorth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtJpanen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtWest)
                        .addGap(18, 18, 18)
                        .addComponent(txtCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEast))
                    .addComponent(txtFile))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtJpanen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(txtNorth, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWest, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEast, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(txtSouth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRedActionPerformed
        // TODO add your handling code here:
        String red = evt.getActionCommand(); // láy button=

        if (red.equals("Red")) {
          txtJpanen.setBackground(Color.red);
        }
    }//GEN-LAST:event_txtRedActionPerformed

    private void txtJpanenAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtJpanenAncestorAdded

    }//GEN-LAST:event_txtJpanenAncestorAdded

    private void txtGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGreenActionPerformed
        // TODO add your handling code here:
        String green = evt.getActionCommand();
        if (green.equals("Green")) {
            txtJpanen.setBackground(Color.green);
        }
    }//GEN-LAST:event_txtGreenActionPerformed

    private void txtYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYellowActionPerformed
        // TODO add your handling code here:
        String yllow = evt.getActionCommand();
        if (yllow.equals("Yellow")) {
            txtJpanen.setBackground(Color.yellow);
        }
    }//GEN-LAST:event_txtYellowActionPerformed

    private void txtNorthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNorthActionPerformed
        txtFile.setText("North");
    }//GEN-LAST:event_txtNorthActionPerformed

    private void txtCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCenterActionPerformed
        // TODO add your handling code here:
        txtFile.setText("Center");
    }//GEN-LAST:event_txtCenterActionPerformed

    private void txtEastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEastActionPerformed
        // TODO add your handling code here:
        txtFile.setText("East");
    }//GEN-LAST:event_txtEastActionPerformed

    private void txtSouthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSouthActionPerformed
        // TODO add your handling code here:
        txtFile.setText("South" + "");
    }//GEN-LAST:event_txtSouthActionPerformed

    private void txtWestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWestActionPerformed
        // TODO add your handling code here:
        txtFile.setText("West");
    }//GEN-LAST:event_txtWestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton txtCenter;
    private javax.swing.JButton txtEast;
    private javax.swing.JTextField txtFile;
    private javax.swing.JButton txtGreen;
    private javax.swing.JPanel txtJpanen;
    private javax.swing.JButton txtNorth;
    private javax.swing.JButton txtRed;
    private javax.swing.JButton txtSouth;
    private javax.swing.JButton txtWest;
    private javax.swing.JButton txtYellow;
    // End of variables declaration//GEN-END:variables
}
